language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
install:
  - sudo apt-get install -y graphviz
  - pip install -r requirements/testing.txt
script: py.test --cov=dotter --cov-report=term-missing
after_success:
  - coveralls
